# Generated by Django 2.2.19 on 2021-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211203_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
